initial-commit
AmeliaPessoa/custom-rss pull request #3
Opened 2024-06-11 18:21 UTC by jvalvesdepaiva76

2024-06-11 18:38 UTC, AmeliaPessoa requested changes

2024-06-11 18:38 UTC, AmeliaPessoa commented on crawler/files/results_20240611150225.json
@jvalvesdepaiva76 por favor remove o arquivo de resultado do git.
Coloca a pasta files no .gitignore.

2024-06-11 18:38 UTC, AmeliaPessoa commented on crawler/config/crawler.json
> +{
Para melhor identificação futura renomeia este arquivo para dacoruna.json
Tambem o python pode ser crawlerdacoruna assim como o nome da classe.

2024-06-11 18:38 UTC, AmeliaPessoa commented on crawler/.gitignore
> +venv/
Excelente 👍

2024-06-11 18:38 UTC, AmeliaPessoa commented on crawler/main.py
> +from apify_client import ApifyClient
Acho que precisas add um requirements.txt para instalação desta dependencia

2024-06-18 23:28 UTC, AmeliaPessoa requested changes

2024-06-18 23:28 UTC, AmeliaPessoa commented on crawler/db/init.sql
> +CREATE TABLE website_articles (
Não consegui achar em que tabela são inseridos os dados do site/execução como mencionado no item 1 da tarefa: https://erp.artbiz.solutions/web#id=7606&cids=1&menu_id=113&action=198&active_id=379&model=project.task&view_type=form

2024-06-18 23:28 UTC, AmeliaPessoa commented on crawler/db/init.sql
> +    crawler_execution_date DATE NOT NULL,
Use um único campo do tipo TIMESTAMP para guardar tanto data quanto hora.

2024-06-18 23:28 UTC, AmeliaPessoa commented on crawler/db/init.sql
> +    title VARCHAR(500) NOT NULL,
Precisamos da coluna author mesmo que para este site deixes mesmo NULL.

2024-06-18 23:28 UTC, AmeliaPessoa commented on crawler/.actor/Dockerfile
> +# First, specify the base Docker image.
Adicione o conteudo do documento que vc fez como README.md dentro da pasta crawler: https://docs.google.com/document/d/1XvrTGPnwSJhwNiSQrBrAyc0Lzuq8Z8av9Q9tsDhuoro/edit#heading=h.qbfba2uuyzot

2024-06-20 06:42 UTC, jvalvesdepaiva76 commented on crawler/db/init.sql
> +CREATE TABLE website_articles (
Eu achei que com essas duas tabelas faria mais sentido por causa de repetir alguns valores(Título, descrição e link).
Adaptei a lógica e o BD para os campos exatos que estão na task do odoo👍

2024-06-21 18:07 UTC, AmeliaPessoa approved these changes

2024-06-21 18:08 UTC, merged